name: chocolatine workflow

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

env:
  MIRROR_URL: "git@github.com:EpitechPGEPromo2029/B-DOP-200-BAR-2-1-chocolatine-nilab.sayed.git"
  EXECUTABLES: "minishell2"



jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Run Coding Style Checker
        run: check.sh $(pwd) $(pwd)
      
      - name: Check for Coding Style Errors
        run: |
          if [ -s coding-style-reports.log ]; then
            cat coding-style-reports.log
            exit 1
          fi
  check_program_compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    needs: check_coding_style  # This ensures it runs AFTER coding style check
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile the program
        run: timeout 120 make || { echo "Compilation failed or timed out"; exit 1; }

      - name: Clean up build files
        run: make clean

      - name: Verify Executables
        run: |
          if [ ! -x "$EXECUTABLES" ]; then
            echo "Executable $EXECUTABLES is missing or not executable"
            exit 1
          fi